### ISSUE TITLE
Generator.Client.Desktop load failed

### ISSUE THREAD

**Issue by jaylarkstudios** [taori/Amusoft.VisualStudio.TemplateGenerator#11]
I just cloned the repo and opened the solution in Visual Studio (2017). The project `Generator.Client.Desktop` failed to load. When I try to reload it, I get the following error:

> D:\Dev\TemplateGenerator\src\Generator.Client.Desktop\Generator.Client.Desktop.csproj : error  : Project file is incomplete. Expected imports are missing.

Environment:
Microsoft Visual Studio Professional 2017 Version 15.9.6
Microsoft .NET Framework Version 4.7.03056
Windows 10 Pro

If you need any other info from me, let me know.

**Comment by taori** [comment]
What is your netcore sdk version? For the *.Desktop assembly i've used a preview version, which might not be installed on your system yet. 

Downloading the latest version from https://dotnet.microsoft.com/download/dotnet-core/3.0 should potentially resolve your issue.

**Comment by jaylarkstudios** [comment]
I installed it, but the issue persists.
The .NET Core 3.0 download page says it should be used with VS 2019, and my team is currently on 2017, so I wonder if that could be causing a problem as well. Once we update to 2019 I'll give it another try.

In the meantime, is there anything else I need to do after having installed 3.0? Do I need to change the project's "Target framework," or is that something different?

**Comment by taori** [comment]
There is temporary support for the netcore 3 sdk in VS2017. The VS Team said this will be removed once vs2019 is fully shipped. try using the search within the options of VS. "netcore" - it's just one checkbox you have to check for it to work. Perhaps a VS reboot will be required

**Comment by alelom** [comment]
Same here, only works in VS2019.

**Comment by taori** [comment]
Yes. The application is a netcore wpf application, which is why at this point VS 2019 is strictly required. If you just want a compiled binary you can get one with just the dotnet sdk though. 

Checkout the sources, go to the project you need and `dotnet build`. I hope that fixes your problem.
