### ISSUE TITLE
Application Doesn't Run

### ISSUE THREAD

**Issue by bjthompson44** [taori/Amusoft.VisualStudio.TemplateGenerator#17]
Downloaded:
https://github.com/taori/Amusoft.VisualStudio.TemplateGenerator/releases/download/1.1.0/Release.zip

Unzipped and ran Generator.Client.Desktop.exe

The application doesn't run. 

Tried to run as admin as well.

**Comment by taori** [comment]
Currently working on updating CI. It seems that for a while broken binaries were being produced. I will tell you once it is fixed.

**Comment by bjthompson44** [comment]
Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by taori** [comment]
@bjthompson44 https://artprodeus21.artifacts.visualstudio.com/Abdfe6578-a405-47e4-8170-2e8df8824373/1af10cc9-3599-4cf0-85f0-3a7f4fa251ed/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3Rhb3JpL3Byb2plY3RJZC8xYWYxMGNjOS0zNTk5LTRjZjAtODVmMC0zYTdmNGZhMjUxZWQvYnVpbGRJZC8xMTUvYXJ0aWZhY3ROYW1lL2Ryb3A1/content?format=file&subPath=%2FTemplateGenerator_1.1.1.140_win64.zip

that should get you started for now so you don't have to wait till i am done with everything

**Comment by bjthompson44** [comment]
Thank you!

**Comment by bjthompson44** [comment]
@taori can't access zip file

**Comment by taori** [comment]
Ok. You'll have to wait a bit. Setting up a github auto release. Probably done shortly.

**Comment by taori** [comment]
https://github.com/taori/Amusoft.VisualStudio.TemplateGenerator/releases/tag/alpha-1.1.1.142

There you go.

**Comment by bjthompson44** [comment]
Thanks, got the source code loading and then got the application working off of the source code.

**Comment by taori** [comment]
Alright. I would appreciate it if you could verify the binary too, just so i know that it works - It does work on my end now too, previously it did not (i tried some alpha SingleFile deployment previously)

**Comment by bjthompson44** [comment]
@taori binary is working.  App ran and created a template then created new solution using template.  All good.  Thanks!

**Comment by taori** [comment]
You're welcome.
