### ISSUE TITLE
Source Code Generator.Client.Desktop fails to load

### ISSUE THREAD

**Issue by bjthompson44** [taori/Amusoft.VisualStudio.TemplateGenerator#18]
Downloaded source
Tried to open solution
Generator.Client.Desktop fails to load

**Comment by taori** [comment]
You need VS 2019 because it is a netcore desktop application. What's your environment?

**Comment by bjthompson44** [comment]
2019

**Comment by taori** [comment]
Care to share screenshots? There should be something in the IDE telling you why this happens. I suppose it's a missing SDK
